### ISSUE TITLE
(MOBILE) Leaderboard - Fix paddings and wallet address format

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#10]
link to design https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=327%3A6393&mode=design&t=KXSEf5gWoZEBRCX9-1

1. Remove paddings on the side (see design) <img width="727" alt="Screenshot 2023-11-17 at 18 17 14" src="https://github.com/TowneSquare/cred/assets/139227890/2a2aef2a-df8f-4518-aff7-aeb9bb6724df">
.
.
2. Wallet address should have the format: 0xYY...ZZ, so a total of 6 characters + ... (see design)
<img width="685" alt="Screenshot 2023-11-17 at 18 18 15" src="https://github.com/TowneSquare/cred/assets/139227890/c5b269a1-d180-44e4-98ad-de187d599712">
.
.

3. Tapping on the address should open the address on aptos Explorer (for example like this https://explorer.aptoslabs.com/account/0x16b447ea5e665fc9c7dfe6c130311a80a1cba37acf945bb8ef58c330cfd4dfc1/transactions?network=mainnet) 
<img width="298" alt="Screenshot 2023-11-17 at 18 24 35" src="https://github.com/TowneSquare/cred/assets/139227890/9cd45fa9-adfb-4fb7-87e3-0a219468835d">

**Comment by markots** [comment]
Approved
