### ISSUE TITLE
[Mobile] Improve "back to top" btn position

### ISSUE THREAD

**Issue by markots** [TowneSquare/cred#106]
btn size needs to be 44px

Figma
https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=3154%3A31735&mode=design&t=PHutC7xjrNPQ8pha-1

<img width="320" alt="Screenshot 2024-01-23 alle 21 24 43" src="https://github.com/TowneSquare/cred/assets/112094900/592cca4b-c1d6-4a4a-916e-8a063f9b6db8">

**Comment by ddamazz** [comment]
@codewizard870 the size and position is still not right 
![image](https://github.com/TowneSquare/cred/assets/139227890/083f0d5c-cd86-4cbd-b2d7-7de4bb6a84f6)

**Comment by realjzhang** [comment]
@codewizard870 please revisit this comment from Nikola above

**Comment by ddamazz** [comment]
fixed, it can be closed @markots

**Comment by markots** [comment]
done
