### ISSUE TITLE
Fix how the X handles look on the reduced width of the browser 

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#107]
Currently when you reduce the width of the browser, the names look like this
<img width="1083" alt="Screenshot 2024-01-23 at 22 21 37" src="https://github.com/TowneSquare/cred/assets/139227890/98fcf8a5-1c9c-48fa-80a2-8c85bec21e68">

Should be like this
<img width="489" alt="Screenshot 2024-01-23 at 22 23 20" src="https://github.com/TowneSquare/cred/assets/139227890/1aa20fca-73c2-4f20-b5ff-738865d269d4">

**Comment by ddamazz** [comment]
@codewizard870 the truncation of the handles should only happen when the you reduce the width of the browser, i.e. when you resize the browser. Otherwise the handles should be displayed fully. If it's not clear pls ask on discord
<img width="1304" alt="Screenshot 2024-01-24 at 13 24 21" src="https://github.com/TowneSquare/cred/assets/139227890/f01bddfb-a82f-4e15-b612-c6d9e4c8ae0a">

**Comment by realjzhang** [comment]
Hi @codewizard870 @d2Dreamer . Please check the comment for instruction from Nikola above
