### ISSUE TITLE
Switching from "Visitor" to "Regular" Cred Point page on wallet change

### ISSUE THREAD

**Issue by markots** [TowneSquare/cred#111]
There's an issue for users who initially explore the Cred visitor page using a new wallet. When they disconnect this new wallet and connect a verified one, the system should ideally display the regular Cred point page. However, currently, it continues to show the Visitor Cred point page.

The expected behavior is for the page to automatically update to the regular Cred point page when a verified wallet is connected.

![image](https://github.com/TowneSquare/cred/assets/112094900/973da4e1-fd3f-4cbf-ba55-3ba2297a2606)

**Comment by codewizard870** [comment]
Currently :
To check visitor mode, user connect their wallet ( at least empty new wallet ).

**Comment by realjzhang** [comment]
For users to visit in visitor mode, they don't need to connect ANY wallet

**Comment by codewizard870** [comment]
But
wallet address it required when they connect their X/discord account directly from visitor mode.

**Comment by realjzhang** [comment]
i checked the current flow again. this approach is ok

**Comment by markots** [comment]
done
