### ISSUE TITLE
[V2] Signed in user is stuck on the V2 connect X/Discord page after connecting X/Discord

### ISSUE THREAD

**Issue by realjzhang** [TowneSquare/cred#114]
For a user that is signed in in our V1 database already, when they sign in on V2, they get stuck on the V2 connect X/Discord page after connecting X/Discord

Correct flow: they should be directed to points page after X connection is verified
https://github.com/TowneSquare/cred/assets/55252633/325f0eb0-0c2e-48c1-a2a8-3c1a9f20c0c4

**Comment by d2Dreamer** [comment]
Related to Backend returning Error.
