### ISSUE TITLE
[V2] Profile ANS selection: when mouse hovers over ANS, both/all ANSs are highlighted

### ISSUE THREAD

**Issue by realjzhang** [TowneSquare/cred#115]
when mouse hovers over ANS, user can still select one ANS, but both/all ANSs are highlighted

Correct flow: only the ANS right under the mouse should be highlighted
![Screenshot 2024-01-25 at 10 29 19](https://github.com/TowneSquare/cred/assets/55252633/24fa0347-8990-47c3-88c0-fdc4af992955)

**Comment by d2Dreamer** [comment]
Attached a branch with a change, don't have 2 ANS addresses to test this so if someone could test it I would appreciate it.
