### ISSUE TITLE
Add the tooltip when user has received the reward in my profile

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#122]
<img width="700" alt="Screenshot 2024-01-28 at 14 00 45" src="https://github.com/TowneSquare/cred/assets/139227890/8abaca94-c261-469c-994a-fc92b0ecb9b6">

The tooltip should be applied to **all green checkmarks on the page!**

design: https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=1855%3A39157&mode=design&t=I9zfpeSGYgPcQUAR-1

desktop: the tooltip appears on hover
mobile: the tooltip appears on tap

**Comment by ddamazz** [comment]
there's no tooltip. Have you pushed it to vercel? @codewizard870 

https://github.com/TowneSquare/cred/assets/139227890/4e9f9bb9-990a-4c0e-9c75-41358fe1b7df

**Comment by ddamazz** [comment]
@codewizard870 the tooltip is still not visible in PROD

**Comment by ddamazz** [comment]
@codewizard870  the tooltip is still not visible in PROD

**Comment by codewizard870** [comment]
It's done just now.
