### ISSUE TITLE
Add tooltip with rewards

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#126]
desktop 
https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=3547%3A30421&mode=design&t=ZT0Co5o1fy1jrwrY-1

<img width="700" alt="Screenshot 2024-02-06 at 18 53 05" src="https://github.com/TowneSquare/cred/assets/139227890/28b9fc4b-bc25-48e3-912e-bc965225860d">

tooltip appears on HOVER

.
.

mobile
https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=1859%3A15851&mode=design&t=ZT0Co5o1fy1jrwrY-1
<img width="381" alt="Screenshot 2024-02-06 at 18 53 52" src="https://github.com/TowneSquare/cred/assets/139227890/883518c9-4424-49fc-8349-526aae27536e">

tooltip appears on TAP
.

@codewizard870

**Comment by codewizard870** [comment]
@ddamazz  
Is this tooltip for only this eligible token list?
