### ISSUE TITLE
(MOBILE) Change share button and position [Improvement]

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#14]
design link https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=327%3A6393&mode=design&t=G6ZAQljHw7lzHBvd-1

<img width="271" alt="Screenshot 2023-11-17 at 21 07 45" src="https://github.com/TowneSquare/cred/assets/139227890/139d0e3d-c855-40ab-a103-d006fd1004f0">

**Comment by markots** [comment]
Approved
