### ISSUE TITLE
(DESKTOP) (TABET) (MOBILE) Add Terms of Service next to Privacy policy

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#16]
<img width="326" alt="Screenshot 2023-11-21 at 10 13 50" src="https://github.com/TowneSquare/cred/assets/139227890/c67dedd3-40b9-43c8-8cb0-b3055077328f">

↑ design mobile https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=318%3A13349&mode=design&t=D6ZssiZZilE3wM49-1

<img width="826" alt="Screenshot 2023-11-21 at 10 14 41" src="https://github.com/TowneSquare/cred/assets/139227890/69d5acc3-16ac-4ee3-8f94-802c7d98e94d">

↑ design desktop https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=295%3A6324&mode=design&t=D6ZssiZZilE3wM49-1

**Comment by ddamazz** [comment]
<img width="793" alt="Screenshot 2023-11-21 at 18 25 41" src="https://github.com/TowneSquare/cred/assets/139227890/3f58cf3b-846e-4c3f-8b30-fbce4d945291">

@townesquarexyz should be a link that leads to https://twitter.com/TowneSquarexyz

@codewizard870

**Comment by ddamazz** [comment]
<img width="623" alt="Screenshot 2023-11-21 at 18 28 56" src="https://github.com/TowneSquare/cred/assets/139227890/c2782211-bea6-4e48-8a92-eb7e47951e73">

link is green, on hover is underscored

**Comment by markots** [comment]
- [ ] Please double check and create a link for "@townesquarexyz" in the Privacy text.

<img width="410" alt="Screenshot 2023-11-24 alle 11 02 59" src="https://github.com/TowneSquare/cred/assets/112094900/9ecdbf2e-eba4-40d8-8d57-ad14bcf56ce0">
<img width="705" alt="Screenshot 2023-11-24 alle 11 03 13" src="https://github.com/TowneSquare/cred/assets/112094900/b612ea0c-92d8-4d20-8a25-91ea4677cca1">


- [ ] Link need to be just "@townesquarexyz" not "@townesquarexyz X"
<img width="236" alt="Screenshot 2023-11-24 alle 11 02 06" src="https://github.com/TowneSquare/cred/assets/112094900/1d813ac4-e18d-4bb9-86d0-2078a11ca1dc">

**Comment by markots** [comment]
Approved
