### ISSUE TITLE
Cred points - Change DeFi names, Panecakeswap image is missing

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#18]
<img width="472" alt="Screenshot 2023-11-21 at 17 31 03" src="https://github.com/TowneSquare/cred/assets/139227890/b242f829-4436-45c5-b1a3-7f9c954f7284">

1. The names of DeFies should be:
PancakeSwap
Liquidswap
Thala
Aries Market

Please use the exact namings with these proper spacings and capital letters

2. PancakeSwap logo image is missing, also pls check if other images are visible. As a reminder always include also x2 image for retina displays

**Comment by ddamazz** [comment]
change Panecake to PancakeSwap 
also pls put Liquidswap an Aries Market here so that we can test these names as well
@codewizard870 
<img width="589" alt="Screenshot 2023-11-21 at 18 14 11" src="https://github.com/TowneSquare/cred/assets/139227890/6e53ed51-b060-4cc8-890c-48a6d5409c2a">

**Comment by markots** [comment]
Approved
