### ISSUE TITLE
Leaderboard - Top boxes with KPIs should have the same width as the container box under them

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#22]
see figma design for specs https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=667%3A10338&mode=design&t=D6ZssiZZilE3wM49-1

<img width="1015" alt="Screenshot 2023-11-21 at 18 18 45" src="https://github.com/TowneSquare/cred/assets/139227890/f6bbf720-5921-46d1-9c7b-0c7dd93bf8eb">

Top boxes are too wide, they should be in line with the container box bellow

**Comment by markots** [comment]
Approved
