### ISSUE TITLE
Leaderboard - The width of the top boxes and bottom container should match

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#23]
<img width="879" alt="Screenshot 2023-11-21 at 18 20 10" src="https://github.com/TowneSquare/cred/assets/139227890/d502b1f8-3faa-45fc-b12c-c41a80016c3b">

The width of the top boxes and bottom container should match

check figma design for specs
https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=295%3A6598&mode=design&t=D6ZssiZZilE3wM49-1

**Comment by markots** [comment]
Approved
