### ISSUE TITLE
(MOBILE) Cred points and Leaderboard - Fix KPI box paddings

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#24]
<img width="232" alt="Screenshot 2023-11-21 at 18 22 28" src="https://github.com/TowneSquare/cred/assets/139227890/5bba966b-9a80-4df0-beed-3fa3377d32c4">

Padding between KPI boxes should be fixed 16px
Padding on the left should be 16px

**Comment by markots** [comment]
Approved
