### ISSUE TITLE
[DESKTOP] Hover state for DeFi transactions

### ISSUE THREAD

**Issue by markots** [TowneSquare/cred#25]
![image](https://github.com/TowneSquare/cred/assets/112094900/5db576c9-b894-49df-bf20-ddf81727a37a)

**Comment by ddamazz** [comment]
<img width="785" alt="Screenshot 2023-11-23 at 11 40 16" src="https://github.com/TowneSquare/cred/assets/139227890/d9abbef3-b91c-4330-94a6-dc8231f9189c">
Please also fix this @codewizard870 

it should be like this
<img width="693" alt="Screenshot 2023-11-23 at 11 41 18" src="https://github.com/TowneSquare/cred/assets/139227890/800e4ac7-2ce8-41b3-96b3-7d1fa4a123b3">

**Comment by markots** [comment]
I don't see changes requested above https://github.com/TowneSquare/cred/issues/25#issuecomment-1824184333 by @ddamazz 

Please double check @codewizard870

**Comment by markots** [comment]
Approved
