### ISSUE TITLE
[DESKTOP] [TALET] [MOBILE] Update illustrations

### ISSUE THREAD

**Issue by markots** [TowneSquare/cred#26]
<img width="895" alt="Screenshot 2023-11-22 alle 13 22 42" src="https://github.com/TowneSquare/cred/assets/112094900/aa67c449-1b2c-4ede-bc53-4a8285ee081c">

**Comment by ddamazz** [comment]
link to illustrations https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=930%3A14575&mode=design&t=AYyqiKGvRpfCUXni-1 
as a reminder, always include also include @2x images for retina displays @codewizard870

**Comment by ddamazz** [comment]
![image](https://github.com/TowneSquare/cred/assets/139227890/0cfa9311-8a21-4590-8bc3-a0d82715d474)

image is overlapping the logo on mobile @codewizard870

**Comment by markots** [comment]
Approved
