### ISSUE TITLE
(DESKTOP) Intro page improvements

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#28]
<img width="1067" alt="Screenshot 2023-11-22 at 15 07 31" src="https://github.com/TowneSquare/cred/assets/139227890/80c65510-5a4b-47f6-8d79-9e6d084fbbf0">

We have issues on smaller screens where the text is very close to the logo on top, and overlaps with the image on the left.

To overcome this, Privacy policy and TOS links must be fixed at the bottom of the screen, with a 26px distance. Between the Privacy policy and TOS links and the box containing the "Connect wallet to check out your Cred points!" and button, the distance should be fixed 45px.
Spacing between the "Connect wallet" box -> title -> logo should be flexible.

Also, keep in mind that the title should not change position during the animation.  

Once the box with "Connect wallet to check out your Cred points!" and button appears, it should remain visible. 

link to design https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=932%3A15273&mode=design&t=TNpQ0FfSHH0vct0S-1

**Comment by markots** [comment]
Vertical resizing need to be improved.
<img width="1739" alt="Screenshot 2023-11-24 alle 10 53 01" src="https://github.com/TowneSquare/cred/assets/112094900/1db58a5f-0a6b-45c1-8897-f1f9720a7325">

**Comment by markots** [comment]
Please improve following:

- [ ] Once the box with "Connect wallet to check out your Cred points!" and button appears, it should remain visible.
