### ISSUE TITLE
[Leaderboard] Add blur to containers

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#4]
Use this blur: 
backdrop-filter: blur(12.9px);
-webkit-backdrop-filter: blur(12.9px);

color, border color, border radius is the same as in figma

apply blur here

<img width="617" alt="Screenshot 2023-11-14 at 10 35 42" src="https://github.com/TowneSquare/cred/assets/139227890/3f787291-ca4e-4a3d-bad7-09b7aa81c124">

**Comment by markots** [comment]
- [ ] Adjust spacing between elements
<img width="788" alt="Screenshot 2023-11-15 alle 09 12 02" src="https://github.com/TowneSquare/cred/assets/112094900/c5a991b5-de7b-425f-b985-63135c6b10ca">

- [ ] Fix the text weight
<img width="1133" alt="Screenshot 2023-11-15 alle 09 14 24" src="https://github.com/TowneSquare/cred/assets/112094900/89d9ed85-a68f-45dc-a5a6-b3e0f619f7f0">

- [ ] Adjust leaderboard style
border-radius: 16px;
border: 1px solid rgba(255, 255, 255, 0.92);
background: linear-gradient(92deg, rgba(255, 255, 255, 0.14) 0%, rgba(255, 255, 255, 0.00) 111.54%);
backdrop-filter: blur(20px);
- [ ] Adjust colors for 3th place number
<img width="752" alt="Screenshot 2023-11-15 alle 09 16 10" src="https://github.com/TowneSquare/cred/assets/112094900/f90e3dc8-4f3f-46b8-90f4-5ead5572d06a">

**Comment by markots** [comment]
Well done
