### ISSUE TITLE
[Cred points] Remove black areas around components

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#5]
<img width="1074" alt="Screenshot 2023-11-14 at 10 38 35" src="https://github.com/TowneSquare/cred/assets/139227890/f4b3dc1e-91dd-4c1e-9180-193ad7721c0d">

Remove this black areas

**Comment by markots** [comment]
"My total cred point"s still have black background
<img width="429" alt="Screenshot 2023-11-15 alle 09 10 04" src="https://github.com/TowneSquare/cred/assets/112094900/9cf6b85f-415b-4307-b8d7-415cff9ca109">

**Comment by markots** [comment]
- [ ] Black background still visible on MY TOTAL CRED POINTS
<img width="774" alt="Screenshot 2023-11-16 alle 09 18 11" src="https://github.com/TowneSquare/cred/assets/112094900/023b159d-591a-4437-ac9c-9ac881d67df9">
