### ISSUE TITLE
[Wallet/Account dropdown] The wallet/account dropdown should open on click

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#6]
figma with design https://www.figma.com/file/HcJEpaCFW8OLJ7alhCv7fj/Cred?type=design&node-id=395%3A19086&mode=design&t=usjHe9jcBEgedPr6-1

<img width="969" alt="Screenshot 2023-11-14 at 10 48 13" src="https://github.com/TowneSquare/cred/assets/139227890/5550d888-243e-49b7-a219-61140dad811e">

also add all the hover and focus states

**Comment by markots** [comment]
- [ ] Change dropdown icon like in figma
- [ ] Set left / right padding to 24px and top / bottom to 16px
<img width="500" alt="Screenshot 2023-11-16 alle 09 22 50" src="https://github.com/TowneSquare/cred/assets/112094900/b74276c5-8963-4604-bc7d-f1c55d6271ac">

- [ ] Add focus state
<img width="222" alt="Screenshot 2023-11-16 alle 09 26 05" src="https://github.com/TowneSquare/cred/assets/112094900/8a398187-609d-48f6-a1a1-30cd6adfa260">

- [ ] Add background to hover state and exclude font weight change

<img width="522" alt="Screenshot 2023-11-16 alle 09 27 43" src="https://github.com/TowneSquare/cred/assets/112094900/76bff5ea-af23-4a69-a37e-3bd0c82f9a8b">

**Comment by markots** [comment]
Approved
