### ISSUE TITLE
**Priority** Points do not show up after you disconnect your wallet & reconnect your wallet

### ISSUE THREAD

**Issue by realjzhang** [TowneSquare/cred#66]
Issue 01 Points do not show up after you disconnect your wallet & reconnect your wallet

https://github.com/TowneSquare/cred/assets/55252633/5d1dc799-8df4-455f-8963-3f7352dfd301
-----

Issue 02 Points do not show up after you disconnect your wallet & connect another wallet

https://github.com/TowneSquare/cred/assets/55252633/a0c35927-8a30-42ce-816f-8a8aec4fe58f

**Comment by markots** [comment]
Done
