### ISSUE TITLE
[About] Share button is not working

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#7]
pls check this message https://discord.com/channels/@me/1171030358679101440/1173924204559745024

This is the default text
<img width="516" alt="Screenshot 2023-11-14 at 11 07 06" src="https://github.com/TowneSquare/cred/assets/139227890/fbaa50a8-8237-468f-a556-f6b432f420b0">

Hey check out Cred! I’m ranked **[RANK SCORE]** with **[POINTS AMOUNT]** CRED points! 
 What’s your score? Check it out on http://www.cred.xyz

for the [RANK SCORE] in the message, keep in mind that after the number (12) there should be also "th" so it should be written "12th" in the post

the same goes to other numbers so: 1st, 2nd, 3rd, 4th etc

**Comment by markots** [comment]
- [ ] Delete empty spacing
<img width="788" alt="Screenshot 2023-11-16 alle 09 32 07" src="https://github.com/TowneSquare/cred/assets/112094900/5a1277b9-428e-4bef-a474-e78880b719fb">
