### ISSUE TITLE
**Priority** [Desktop] New account signup flow unexpected redirect and reconnect

### ISSUE THREAD

**Issue by realjzhang** [TowneSquare/cred#72]
The following issues showed up on multiple attempts when i tried connect new addresses on CRED.

Issue 1. For new wallet address connecting on CRED, it redirects to the first page with animations after wallet is connected before showing the user the invite code page.
Correct flow: after wallet is connected, the invite code page should directly show up if it's not registered before. The first page with animated texts should not show up.

Issue 2. after inserting invite code, Privacy Policy page shows up first
Correct flow: after inserting invite code, CRED points page should show up directly, not the privacy policy page.

Issue 3. when i tried to click on Cred points page from the Privacy Policy page, it redirects me to the invite code page again
Diagnosis: it seems that address is not fully registered in the backend, hence why i was redirected to the invite code page AGAIN?
Correct flow: when user clicks on CRED points page, it should direct them to the CRED points page

https://github.com/TowneSquare/cred/assets/55252633/509e377d-ad6f-4b78-968e-d5c77228f40c

**Comment by markots** [comment]
Done
