### ISSUE TITLE
Default Profile image should be the gradient, no the smiley face

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#83]
<img width="700" alt="Screenshot 2024-01-22 at 14 37 56" src="https://github.com/TowneSquare/cred/assets/139227890/37b8cf15-e99d-4a86-a2ed-e843ceb8df3c">

The default profile image with the smiley face, should be the same as the one in the top right corner (in my case the yellow green one). Every user has a different gradient which he got randomly

**Comment by codewizard870** [comment]
Please share the detail in group please and discuss.
