### ISSUE TITLE
When X is connected and X handle is selected as the preferred name, the image and the name should also appear in the top right corner

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#86]
Currently it's like this:
<img width="700" alt="Screenshot 2024-01-22 at 15 12 35" src="https://github.com/TowneSquare/cred/assets/139227890/205a496c-3928-4031-adbb-ad17c2662d9a">

It should be like this:
<img width="700" alt="Screenshot 2024-01-22 at 15 15 16" src="https://github.com/TowneSquare/cred/assets/139227890/e16e5cd3-7a45-4465-a25e-91d1d0350374">

Also please check why the image retrieved from X is currently in low resolution and blurry.
<img width="333" alt="Screenshot 2024-01-22 at 15 17 01" src="https://github.com/TowneSquare/cred/assets/139227890/4d050af3-4547-4275-965b-576dc7d561ec">

**Comment by codewizard870** [comment]
Not sure about image is blurry. ( let me check more )
