### ISSUE TITLE
Update the flow when Connecting with X or Discord

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#89]
<img width="670" alt="Screenshot 2024-01-22 at 15 47 06" src="https://github.com/TowneSquare/cred/assets/139227890/d1f48b6b-9bca-4313-a693-8803fbd54ca3">
Current flow

Currently, when a user clicks "Connect X" on the Cred website, it opens a new browser tab showing the @0xcred account on X, and simultaneously navigates from the original tab to the X page. This causes inconvenience as users must manually switch back to the Cred website tab to complete the authorization.

Preferred flow

When a user clicks "Connect X" on the Cred website, the primary focus should remain on the current tab. This keeps the user's workflow uninterrupted and straightforward. In parallel, a new tab can be opened with the @0xcred account on X. This tab should not automatically become the active tab. Instead, it should be available for the user to click and view at their convenience.

**Comment by codewizard870** [comment]
Finding solution.

**Comment by codewizard870** [comment]
window.open('https://discord.gg/bK5p9tNM4d', '_blank', 'noopener,noreferrer,resizable');
this one should be work but not working now.

**Comment by codewizard870** [comment]
![image](https://github.com/TowneSquare/cred/assets/91666375/fb5821ae-6e22-414f-bcb2-226f8e9bfde9)
This one is updated state. please give me feedback about it.

**Comment by ddamazz** [comment]
@codewizard870 it's still not working as it should. If the toggle is ON and I click on connect, I still see first Cred X account page, instead of seeing Authoirze page. 
The flow should be like this: 

1. The user clicks on Connect X. 
2. The user **remains** in the same tab and sees the "Authorize page". User click on Authorize.
3. A new tab opens (www.twitter.com/0xcred) with Cred's X account, but the focus remains on the "Authorize page". The user can later click on the tab with Cred's X account if and when he wants to.


The same applies for Discord as well.

please let me know if further information is needed
