### ISSUE TITLE
It's not possible to connect Discord for new wallets on Mobile. Shows "null"

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/cred#95]
<img width="357" alt="Screenshot 2024-01-22 at 18 05 54" src="https://github.com/TowneSquare/cred/assets/139227890/25671f86-c5fe-46af-9879-bea6b9c0aeea">

https://github.com/TowneSquare/cred/assets/139227890/e0e4f1ce-bcc2-4876-b368-a9bb0cefe9ca

**Comment by codewizard870** [comment]
Backend issue.

**Comment by ddamazz** [comment]
@codewizard870 for Discord it shouldn't lead to discord.com because it's not possible to login to Discord through the site. It should call magic.auth for discord, like it does for TowneSquare
